# Generated by Django 5.1.1 on 2024-10-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_aeropuerto', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_pistas', models.IntegerField()),
                ('tipo_avion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('antiguedad', models.IntegerField()),
                ('aerolinea', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('puertas', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('antiguedad', models.IntegerField()),
                ('especificacion', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=50)),
                ('numeroMotores', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Copiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('discapacidad', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('antiguedad', models.IntegerField()),
                ('turno', models.CharField(max_length=20)),
                ('horasVuelo', models.FloatField()),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=50)),
                ('tiempo_restante', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Helicoptero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('antiguedad', models.IntegerField()),
                ('helices', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('discapacidad', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('discapacidad', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('antiguedad', models.IntegerField()),
                ('turno', models.CharField(max_length=20)),
                ('horasVuelo', models.FloatField()),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=50)),
                ('horas', models.FloatField()),
                ('tipo_aeronave', models.CharField(max_length=50)),
                ('salud_mental', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sobrecargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('discapacidad', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('antiguedad', models.IntegerField()),
                ('turno', models.CharField(max_length=20)),
                ('horasVuelo', models.FloatField()),
                ('genero', models.CharField(max_length=10)),
                ('idiomas', models.CharField(max_length=100)),
                ('certificados', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('ancho', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipajes', to='aereopuerto_app.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_terminal', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminales', to='aereopuerto_app.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('horaSalida', models.DateTimeField()),
                ('horaDestino', models.DateTimeField()),
                ('copiloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aereopuerto_app.copiloto')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aereopuerto_app.piloto')),
                ('sobrecargos', models.ManyToManyField(to='aereopuerto_app.sobrecargo')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aereopuerto_app.terminal')),
                ('vehiculoAereo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aereopuerto_app.avion')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aereopuerto_app.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aereopuerto_app.vuelo')),
            ],
        ),
    ]
