# Generated by Django 5.1.1 on 2024-10-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('idAeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAeropuerto', models.CharField(max_length=255)),
                ('numPistas', models.IntegerField()),
                ('tipoAvion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoAereo',
            fields=[
                ('idVehiculoAereo', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('serie', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('antiguedad', models.CharField(max_length=50)),
                ('tiempoAire', models.FloatField()),
                ('llantas', models.IntegerField()),
                ('tanque', models.CharField(max_length=50)),
                ('distancia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('discapacidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.persona')),
                ('idPasajero', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            bases=('aereopuerto_app.persona',),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('idTerminal', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('idAeropuerto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to='aereopuerto_app.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('idVuelo', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('duracion', models.TimeField()),
                ('horaSalida', models.CharField(max_length=50)),
                ('horaLlegada', models.CharField(max_length=50)),
                ('idTerminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vuelo', to='aereopuerto_app.terminal')),
                ('idVehiculoAereo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vuelo', to='aereopuerto_app.vehiculoaereo')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('vehiculoaereo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.vehiculoaereo')),
                ('idAvion', models.AutoField(primary_key=True, serialize=False)),
                ('aerolinea', models.CharField(max_length=100)),
                ('tipoMotor', models.CharField(max_length=100)),
                ('puertas', models.IntegerField()),
                ('tipoAvion', models.CharField(max_length=50)),
                ('vehiculo_aereo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avion_vehiculo_aereo', to='aereopuerto_app.vehiculoaereo')),
            ],
            bases=('aereopuerto_app.vehiculoaereo',),
        ),
        migrations.CreateModel(
            name='Avioneta',
            fields=[
                ('vehiculoaereo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.vehiculoaereo')),
                ('idAvioneta', models.AutoField(primary_key=True, serialize=False)),
                ('numeroMotores', models.IntegerField()),
                ('tipoPista', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=50)),
                ('tipoConcesion', models.CharField(max_length=50)),
                ('vehiculo_aereo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avioneta_vehiculo_aereo', to='aereopuerto_app.vehiculoaereo')),
            ],
            bases=('aereopuerto_app.vehiculoaereo',),
        ),
        migrations.CreateModel(
            name='Helicoptero',
            fields=[
                ('vehiculoaereo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.vehiculoaereo')),
                ('idHelicoptero', models.AutoField(primary_key=True, serialize=False)),
                ('numeroHelices', models.IntegerField()),
                ('tipoHelicoptero', models.CharField(max_length=50)),
                ('vehiculo_aereo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helicoptero_vehiculo_aereo', to='aereopuerto_app.vehiculoaereo')),
            ],
            bases=('aereopuerto_app.vehiculoaereo',),
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('idEquipaje', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.CharField(max_length=50)),
                ('altura', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('idPasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipajes', to='aereopuerto_app.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('idBoleto', models.AutoField(primary_key=True, serialize=False)),
                ('asiento', models.CharField(max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idVuelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='aereopuerto_app.vuelo')),
                ('idPasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='aereopuerto_app.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.persona')),
                ('idTripulacion', models.AutoField(primary_key=True, serialize=False)),
                ('antiguedad', models.IntegerField()),
                ('turno', models.CharField(max_length=50)),
                ('horasVuelo', models.FloatField()),
                ('genero', models.CharField(max_length=10)),
                ('idVuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='aereopuerto_app.vuelo')),
            ],
            bases=('aereopuerto_app.persona',),
        ),
        migrations.CreateModel(
            name='Copiloto',
            fields=[
                ('tripulacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.tripulacion')),
                ('idCopiloto', models.AutoField(primary_key=True, serialize=False)),
                ('rango', models.CharField(max_length=50)),
                ('tiempoRestantePiloto', models.TimeField()),
                ('tripulacion_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copiloto_tripulacion', to='aereopuerto_app.tripulacion')),
            ],
            bases=('aereopuerto_app.tripulacion',),
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('tripulacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.tripulacion')),
                ('idPiloto', models.AutoField(primary_key=True, serialize=False)),
                ('rango', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=50)),
                ('tipoAeronave', models.CharField(max_length=50)),
                ('saludMental', models.CharField(max_length=50)),
                ('tripulacion_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_tripulacion', to='aereopuerto_app.tripulacion')),
            ],
            bases=('aereopuerto_app.tripulacion',),
        ),
        migrations.CreateModel(
            name='Sobrecargo',
            fields=[
                ('tripulacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aereopuerto_app.tripulacion')),
                ('idSobrecargo', models.AutoField(primary_key=True, serialize=False)),
                ('idiomas', models.CharField(max_length=255)),
                ('certificados', models.CharField(max_length=255)),
                ('tripulacion_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sobrecargo_tripulacion', to='aereopuerto_app.tripulacion')),
            ],
            bases=('aereopuerto_app.tripulacion',),
        ),
    ]
